### PR TITLE
Support binary release for both glibc 2.12 (or earlier like centos6) and 2.14 (or later like ubuntu14 or centos7)

### PR DESCRIPTION
**Pull request by matsumoto-r**
ref: #3 

rcon supports binary release using @hsbt 's https://github.com/hsbt/mackerel-plugin-sidekiq-job-count as a reference. 

@rrreeeyyy Please check it! I'll release rcon binary after merging this.

### CODE REVIEW

**Comment by hsbt** [comment]
Thanks to use my dirty code :innocent: 

I will make to proposal more better code to mruby-cli for binary packaging task.

**Comment by matsumoto-r** [comment]
OK, I just now support both glibc 2.12 and 2.14 or later binary.

**Comment by matsumoto-r** [comment]
release binary name

image

**Comment by rrreeeyyy** [comment]
@matsumoto-r Iooks good to me! both glibc 2.12 and 2.14 support is really awesome!

**Comment by matsumoto-r** [comment]
@rrreeeyyy Thank you for your review and noticing!! Merged now.

**Pull request merged**
